# Generated by Django 4.1.1 on 2022-09-19 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='category/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='colections/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(blank=True, max_length=225, null=True)),
                ('type', models.CharField(choices=[('f', 'Feature'), ('i', 'Infographic'), ('g', 'Gallery')], max_length=1)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('gallery_1', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('gallery_2', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('gallery_3', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('gallery_4', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
