# Generated by Django 4.1.1 on 2022-09-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.collections'),
        ),
    ]
