# Generated by Django 4.1.1 on 2022-09-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
