# Generated by Django 4.1.1 on 2022-09-21 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_comments_date_alter_products_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 23, 6, 3, 886611)),
        ),
    ]
