# Generated by Django 4.1.1 on 2022-09-26 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='product.category'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 8, 20, 15, 417004)),
        ),
    ]
