# Generated by Django 4.1.1 on 2022-09-27 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_comments_date_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 5, 12, 44, 293821)),
        ),
    ]
