# Generated by Django 4.1.1 on 2022-09-19 08:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(max_length=225)),
                ('logo', models.ImageField(upload_to='logo/%y/%m/%d')),
                ('phone', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=225)),
                ('about', ckeditor.fields.RichTextField()),
                ('copyright', models.CharField(max_length=225)),
            ],
        ),
    ]
