# Generated by Django 4.1.1 on 2022-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
