# Generated by Django 4.1.1 on 2022-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_address_cart_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('POSTING', 'POSTING'), ('DELIEVERED', 'DELIEVERED')], default='PENDING', max_length=10),
        ),
    ]
